// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todo_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Task) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type CreateTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskRequest) Reset()         { *m = CreateTaskRequest{} }
func (m *CreateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTaskRequest) ProtoMessage()    {}
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *CreateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskRequest.Unmarshal(m, b)
}
func (m *CreateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskRequest.Marshal(b, m, deterministic)
}
func (m *CreateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskRequest.Merge(m, src)
}
func (m *CreateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTaskRequest.Size(m)
}
func (m *CreateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskRequest proto.InternalMessageInfo

func (m *CreateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CreateTaskResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTaskResponse) Reset()         { *m = CreateTaskResponse{} }
func (m *CreateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTaskResponse) ProtoMessage()    {}
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *CreateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTaskResponse.Unmarshal(m, b)
}
func (m *CreateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTaskResponse.Marshal(b, m, deterministic)
}
func (m *CreateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTaskResponse.Merge(m, src)
}
func (m *CreateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTaskResponse.Size(m)
}
func (m *CreateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTaskResponse proto.InternalMessageInfo

func (m *CreateTaskResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadTaskRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTaskRequest) Reset()         { *m = ReadTaskRequest{} }
func (m *ReadTaskRequest) String() string { return proto.CompactTextString(m) }
func (*ReadTaskRequest) ProtoMessage()    {}
func (*ReadTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *ReadTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTaskRequest.Unmarshal(m, b)
}
func (m *ReadTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTaskRequest.Marshal(b, m, deterministic)
}
func (m *ReadTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTaskRequest.Merge(m, src)
}
func (m *ReadTaskRequest) XXX_Size() int {
	return xxx_messageInfo_ReadTaskRequest.Size(m)
}
func (m *ReadTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTaskRequest proto.InternalMessageInfo

func (m *ReadTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadTaskResponse) Reset()         { *m = ReadTaskResponse{} }
func (m *ReadTaskResponse) String() string { return proto.CompactTextString(m) }
func (*ReadTaskResponse) ProtoMessage()    {}
func (*ReadTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *ReadTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadTaskResponse.Unmarshal(m, b)
}
func (m *ReadTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadTaskResponse.Marshal(b, m, deterministic)
}
func (m *ReadTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadTaskResponse.Merge(m, src)
}
func (m *ReadTaskResponse) XXX_Size() int {
	return xxx_messageInfo_ReadTaskResponse.Size(m)
}
func (m *ReadTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadTaskResponse proto.InternalMessageInfo

func (m *ReadTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskRequest) Reset()         { *m = UpdateTaskRequest{} }
func (m *UpdateTaskRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskRequest) ProtoMessage()    {}
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{5}
}

func (m *UpdateTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskRequest.Unmarshal(m, b)
}
func (m *UpdateTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskRequest.Merge(m, src)
}
func (m *UpdateTaskRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskRequest.Size(m)
}
func (m *UpdateTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskRequest proto.InternalMessageInfo

func (m *UpdateTaskRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateTaskResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTaskResponse) Reset()         { *m = UpdateTaskResponse{} }
func (m *UpdateTaskResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTaskResponse) ProtoMessage()    {}
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{6}
}

func (m *UpdateTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTaskResponse.Unmarshal(m, b)
}
func (m *UpdateTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTaskResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTaskResponse.Merge(m, src)
}
func (m *UpdateTaskResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTaskResponse.Size(m)
}
func (m *UpdateTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTaskResponse proto.InternalMessageInfo

func (m *UpdateTaskResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskRequest) Reset()         { *m = DeleteTaskRequest{} }
func (m *DeleteTaskRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskRequest) ProtoMessage()    {}
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{7}
}

func (m *DeleteTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskRequest.Unmarshal(m, b)
}
func (m *DeleteTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskRequest.Merge(m, src)
}
func (m *DeleteTaskRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskRequest.Size(m)
}
func (m *DeleteTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskRequest proto.InternalMessageInfo

func (m *DeleteTaskRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTaskResponse) Reset()         { *m = DeleteTaskResponse{} }
func (m *DeleteTaskResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTaskResponse) ProtoMessage()    {}
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{8}
}

func (m *DeleteTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTaskResponse.Unmarshal(m, b)
}
func (m *DeleteTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTaskResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTaskResponse.Merge(m, src)
}
func (m *DeleteTaskResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTaskResponse.Size(m)
}
func (m *DeleteTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTaskResponse proto.InternalMessageInfo

type ListTasksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksRequest) Reset()         { *m = ListTasksRequest{} }
func (m *ListTasksRequest) String() string { return proto.CompactTextString(m) }
func (*ListTasksRequest) ProtoMessage()    {}
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{9}
}

func (m *ListTasksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksRequest.Unmarshal(m, b)
}
func (m *ListTasksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksRequest.Marshal(b, m, deterministic)
}
func (m *ListTasksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksRequest.Merge(m, src)
}
func (m *ListTasksRequest) XXX_Size() int {
	return xxx_messageInfo_ListTasksRequest.Size(m)
}
func (m *ListTasksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksRequest proto.InternalMessageInfo

type ListTasksResponse struct {
	Task                 []*Task  `protobuf:"bytes,1,rep,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTasksResponse) Reset()         { *m = ListTasksResponse{} }
func (m *ListTasksResponse) String() string { return proto.CompactTextString(m) }
func (*ListTasksResponse) ProtoMessage()    {}
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{10}
}

func (m *ListTasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTasksResponse.Unmarshal(m, b)
}
func (m *ListTasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTasksResponse.Marshal(b, m, deterministic)
}
func (m *ListTasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTasksResponse.Merge(m, src)
}
func (m *ListTasksResponse) XXX_Size() int {
	return xxx_messageInfo_ListTasksResponse.Size(m)
}
func (m *ListTasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTasksResponse proto.InternalMessageInfo

func (m *ListTasksResponse) GetTask() []*Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "todo.proto.Task")
	proto.RegisterType((*CreateTaskRequest)(nil), "todo.proto.CreateTaskRequest")
	proto.RegisterType((*CreateTaskResponse)(nil), "todo.proto.CreateTaskResponse")
	proto.RegisterType((*ReadTaskRequest)(nil), "todo.proto.ReadTaskRequest")
	proto.RegisterType((*ReadTaskResponse)(nil), "todo.proto.ReadTaskResponse")
	proto.RegisterType((*UpdateTaskRequest)(nil), "todo.proto.UpdateTaskRequest")
	proto.RegisterType((*UpdateTaskResponse)(nil), "todo.proto.UpdateTaskResponse")
	proto.RegisterType((*DeleteTaskRequest)(nil), "todo.proto.DeleteTaskRequest")
	proto.RegisterType((*DeleteTaskResponse)(nil), "todo.proto.DeleteTaskResponse")
	proto.RegisterType((*ListTasksRequest)(nil), "todo.proto.ListTasksRequest")
	proto.RegisterType((*ListTasksResponse)(nil), "todo.proto.ListTasksResponse")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0x81, 0x36, 0xff, 0xd0, 0x21, 0xf9, 0xdb, 0x4e, 0x3c, 0x34, 0x15, 0x0c, 0x56, 0x0e,
	0x9c, 0x7a, 0xc0, 0x8b, 0x78, 0xd5, 0x44, 0x63, 0xe4, 0x52, 0xf1, 0x01, 0x2a, 0x3b, 0x87, 0x06,
	0x75, 0x6b, 0x77, 0x35, 0xbe, 0x85, 0xaf, 0x6c, 0xba, 0x14, 0x76, 0xdb, 0x52, 0xa3, 0xde, 0x36,
	0x33, 0xdf, 0x7c, 0xfb, 0xcd, 0xfc, 0x00, 0x24, 0x67, 0x3c, 0xca, 0x72, 0x2e, 0x39, 0x1a, 0xef,
	0xf0, 0x06, 0xec, 0x65, 0x22, 0xd6, 0xf8, 0x1f, 0x7a, 0x29, 0xf3, 0xbb, 0xe3, 0xee, 0xd4, 0x89,
	0x7b, 0x29, 0x43, 0x04, 0x5b, 0xd2, 0x87, 0xf4, 0x7b, 0xaa, 0xa2, 0xde, 0x38, 0x04, 0x67, 0xc5,
	0x9f, 0xb3, 0x27, 0x92, 0xc4, 0x7c, 0x6b, 0xdc, 0x9d, 0xf6, 0x63, 0x5d, 0x08, 0xe7, 0xe0, 0x5d,
	0xe6, 0x94, 0x48, 0x2a, 0xfc, 0x62, 0x7a, 0x7d, 0x23, 0x21, 0x71, 0x02, 0xb6, 0x4c, 0xc4, 0x5a,
	0x19, 0x0f, 0x66, 0x6e, 0xa4, 0x7f, 0x8e, 0x94, 0x4c, 0x75, 0xc3, 0x09, 0xa0, 0x39, 0x2a, 0x32,
	0xfe, 0x22, 0xa8, 0x1e, 0x29, 0x3c, 0x81, 0x83, 0x98, 0x12, 0x66, 0xda, 0xd7, 0x25, 0xe7, 0xe0,
	0x6a, 0x49, 0x69, 0xf3, 0xb3, 0x08, 0x73, 0xf0, 0x1e, 0x32, 0xf6, 0xa7, 0xf4, 0x17, 0x80, 0xe6,
	0xe8, 0xaf, 0xbe, 0x3d, 0x05, 0xef, 0x8a, 0x8a, 0xfb, 0x7d, 0xb7, 0xd5, 0x21, 0xa0, 0x29, 0xda,
	0x7c, 0x10, 0x22, 0xb8, 0x77, 0xa9, 0x90, 0x45, 0x4d, 0x94, 0x93, 0xc5, 0x16, 0x46, 0xad, 0x91,
	0xc4, 0x6a, 0x4f, 0x32, 0xfb, 0xb4, 0x60, 0xb0, 0xe4, 0x8c, 0xdf, 0x53, 0xfe, 0x9e, 0xae, 0x08,
	0x17, 0x00, 0x9a, 0x09, 0x8e, 0xcc, 0xa9, 0x06, 0xe6, 0xe0, 0xb8, 0xad, 0x5d, 0x66, 0xed, 0xe0,
	0x35, 0xf4, 0xb7, 0x64, 0xf0, 0xc8, 0x54, 0xd7, 0x90, 0x06, 0xc3, 0xfd, 0xcd, 0x9d, 0xd1, 0x02,
	0x40, 0x5f, 0xbb, 0x9a, 0xab, 0x01, 0xb0, 0x9a, 0xab, 0x09, 0x69, 0x63, 0xa7, 0x6f, 0x5b, 0xb5,
	0x6b, 0x80, 0xa9, 0xda, 0xed, 0x41, 0xd2, 0xc1, 0x5b, 0x70, 0x76, 0x00, 0xb0, 0xb2, 0x4a, 0x9d,
	0x55, 0x30, 0x6a, 0xe9, 0x6e, 0xbd, 0x1e, 0xff, 0xa9, 0xd6, 0xd9, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0x34, 0x28, 0xc0, 0xbb, 0x03, 0x00, 0x00,
}
